### PR TITLE
remove unused varnish-init.js overwrite file

### PR DESCRIPTION
**Pull request by dbu**
not that important, but in #10 you stop using this to overwrite. no need to provide the file.

### CODE REVIEW

**Comment by vranac** [comment]
Oh that file is used very much :) https://github.com/netgen/summercamp-2015/blob/master/provisioning/roles/varnish/tasks/main.yml#L16

**Comment by dbu** [comment]
no, you use varnish-defaults.j2 there, not varnish-init.js2

i remove only the file you removed from the ansible file in #10

**Comment by vranac** [comment]
The file was just renamed, from varnish-init.j2 to varnish-defaults.j2 in https://github.com/netgen/summercamp-2015/commit/d62f8dad4bc6e5eb34be76c0fc7d881d305fed1f after you opened the issue

**Comment by dbu** [comment]
ah, ok. and now i also see why things did not work before...

**Pull request closed without merging**
